version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    exclude-paths:
      - "src/test/resources/**"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
